# Generated by Django 2.0.5 on 2018-05-26 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='create_by',
            new_name='created_by',
        ),
    ]
